name: JBTCD Release Action
description: A GitHub Action for auto tagging your repository
branding:
  icon: activity
  color: orange
inputs:
  current-version:
    description: Current version of the repository
    required: true
    default: 0.0.0
runs:
  using: node12
  main: index.js