name: JBTCD Release Action
description: A GitHub Action for auto tagging your repository
branding:
  icon: activity
  color: orange
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World
outputs:
  time:
    description: The time we greeted you
runs:
  using: node12
  main: index.js